version: "3.7"
services:
  sftp:
    image: custom_sftp:latest
    container_name: custom_sftp
    volumes:
        - ./upload:/home/admin/upload
    ports:
        - "40:22"
    command: admin:admin:1001
    networks:
      - default

networks:
  default:
    driver: bridge
